pub const PREFIX: &str = "/backend/v3/api";

pub const ROUTES: &[(&str, &str, &str)] = &[
    ("GET", "/backend/v3/api/forum/nodes", "nodes.list"),
    ("POST", "/backend/v3/api/forum/nodes", "nodes.create"),
    (
        "PATCH",
        "/backend/v3/api/forum/nodes/{nodeId}",
        "nodes.update",
    ),
    (
        "DELETE",
        "/backend/v3/api/forum/nodes/{nodeId}",
        "nodes.delete",
    ),
    (
        "GET",
        "/backend/v3/api/forum/topic_prefixes",
        "topicPrefixes.list",
    ),
    (
        "POST",
        "/backend/v3/api/forum/topic_prefixes",
        "topicPrefixes.create",
    ),
    ("GET", "/backend/v3/api/forum/topics", "topics.list"),
    (
        "GET",
        "/backend/v3/api/forum/topics/{topicId}",
        "topics.retrieve",
    ),
    (
        "PATCH",
        "/backend/v3/api/forum/topics/{topicId}",
        "topics.update",
    ),
    (
        "DELETE",
        "/backend/v3/api/forum/topics/{topicId}",
        "topics.delete",
    ),
    (
        "POST",
        "/backend/v3/api/forum/topics/{topicId}/pin",
        "topics.pin.create",
    ),
    (
        "DELETE",
        "/backend/v3/api/forum/topics/{topicId}/pin",
        "topics.pin.delete",
    ),
    (
        "POST",
        "/backend/v3/api/forum/topics/{topicId}/feature",
        "topics.feature.create",
    ),
    (
        "DELETE",
        "/backend/v3/api/forum/topics/{topicId}/feature",
        "topics.feature.delete",
    ),
    (
        "POST",
        "/backend/v3/api/forum/topics/{topicId}/lock",
        "topics.lock.create",
    ),
    (
        "DELETE",
        "/backend/v3/api/forum/topics/{topicId}/lock",
        "topics.lock.delete",
    ),
    (
        "POST",
        "/backend/v3/api/forum/topics/{topicId}/move",
        "topics.move.create",
    ),
    (
        "GET",
        "/backend/v3/api/forum/moderation/queue",
        "moderation.queue.list",
    ),
    (
        "GET",
        "/backend/v3/api/forum/moderation/cases",
        "moderation.cases.list",
    ),
    (
        "POST",
        "/backend/v3/api/forum/moderation/cases",
        "moderation.cases.create",
    ),
    (
        "GET",
        "/backend/v3/api/forum/moderation/cases/{caseId}",
        "moderation.cases.retrieve",
    ),
    (
        "POST",
        "/backend/v3/api/forum/moderation/cases/{caseId}/decisions",
        "moderation.cases.decisions.create",
    ),
    ("GET", "/backend/v3/api/forum/sanctions", "sanctions.list"),
    (
        "POST",
        "/backend/v3/api/forum/sanctions",
        "sanctions.create",
    ),
    (
        "PATCH",
        "/backend/v3/api/forum/sanctions/{sanctionId}",
        "sanctions.update",
    ),
    (
        "GET",
        "/backend/v3/api/forum/reputation/rules",
        "reputation.rules.list",
    ),
    (
        "POST",
        "/backend/v3/api/forum/reputation/rules",
        "reputation.rules.create",
    ),
    (
        "GET",
        "/backend/v3/api/forum/reputation/ledger",
        "reputation.ledger.list",
    ),
    (
        "GET",
        "/backend/v3/api/forum/trust_levels",
        "trustLevels.list",
    ),
    (
        "POST",
        "/backend/v3/api/forum/trust_levels",
        "trustLevels.create",
    ),
    ("GET", "/backend/v3/api/forum/badges", "badges.list"),
    ("POST", "/backend/v3/api/forum/badges", "badges.create"),
    (
        "GET",
        "/backend/v3/api/forum/stats/boards",
        "stats.boards.list",
    ),
    (
        "GET",
        "/backend/v3/api/forum/stats/topics",
        "stats.topics.list",
    ),
    (
        "POST",
        "/backend/v3/api/forum/search/reindex",
        "search.reindex.create",
    ),
    (
        "GET",
        "/backend/v3/api/forum/audit/actions",
        "audit.actions.list",
    ),
];
